DROP TABLE IF EXISTS STUDENTS;

CREATE TABLE STUDENTS(
	UID SERIAL,
	NOMBRE VARCHAR(30),
	RUT VARCHAR(15),
	CLASE VARCHAR(30),
	NIVEL INT
);

INSERT INTO STUDENTS (NOMBRE,RUT,CLASE,NIVEL)VALUES
('amadeus mozart','1.123.456-7','piano',10);

SELECT * FROM STUDENTS;